# Generated by Django 5.0 on 2026-03-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vectorstore_path', models.CharField(blank=True, default='', help_text='Path to course-level FAISS vectorstore (relative to MEDIA_ROOT)', max_length=500)),
                ('vectorstore_created', models.BooleanField(db_index=True, default=False, help_text='Has the course-level vectorstore been built?')),
                ('vectorstore_updated_at', models.DateTimeField(blank=True, help_text='When the course vectorstore was last rebuilt', null=True)),
                ('total_videos', models.IntegerField(default=0)),
                ('processed_videos', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='core_course_is_acti_0fcfd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Full Vimeo URL', max_length=500)),
                ('vimeo_video_id', models.CharField(db_index=True, help_text='Extracted Vimeo video ID', max_length=50)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('local_path', models.CharField(blank=True, default='', help_text='Path to downloaded video file', max_length=500)),
                ('audio_path', models.CharField(blank=True, default='', help_text='Path to extracted audio file', max_length=500)),
                ('transcript_path', models.CharField(blank=True, default='', help_text='Path to transcript text file', max_length=500)),
                ('vectorstore_path', models.CharField(blank=True, default='', help_text='Path to FAISS vectorstore directory', max_length=500)),
                ('vectorstore_created', models.BooleanField(db_index=True, default=False, help_text='Has vectorstore been created?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('embedding', 'Creating Embeddings'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Parent course', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.course')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['course', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], db_index=True, default='SCHEDULED', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Processing progress 0-100')),
                ('current_step', models.CharField(blank=True, default='', help_text='Current pipeline step', max_length=50)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_traceback', models.TextField(blank=True, default='')),
                ('worker_id', models.CharField(blank=True, default='', max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('processing_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(help_text='Video being processed', on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='core.video')),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['course', 'is_active'], name='core_video_course__c42f36_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['vimeo_video_id'], name='core_video_vimeo_v_e65e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['vectorstore_created'], name='core_video_vectors_2c484f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('course', 'vimeo_video_id')},
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['video', '-created_at'], name='core_proces_video_i_d9f50e_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'scheduled_at'], name='core_proces_status_9f3937_idx'),
        ),
    ]
