# Generated by Django 5.0 on 2026-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('endpoint', models.CharField(max_length=512)),
                ('request_body', models.TextField(blank=True, default='')),
                ('response_body', models.TextField(blank=True, default='')),
                ('status_code', models.IntegerField(default=0)),
                ('status_text', models.CharField(blank=True, default='', max_length=100)),
                ('latency_ms', models.IntegerField(default=0)),
                ('saved', models.BooleanField(db_index=True, default=False, help_text='True when explicitly saved to history by user')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'saved'], name='core_apical_created_28ec5e_idx')],
            },
        ),
    ]
