# Generated by Django 5.0 on 2026-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apicalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_version',
            field=models.PositiveIntegerField(default=0, help_text='Incremented every time a video is added or removed'),
        ),
        migrations.AddField(
            model_name='course',
            name='vectorstore_version',
            field=models.PositiveIntegerField(default=0, help_text='The content_version the vectorstore was last built for'),
        ),
    ]
