# Generated by Django 5.0 on 2026-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_course_content_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='processing_path',
            field=models.CharField(blank=True, choices=[('vimeo_transcript', 'Fast Path — Vimeo Captions'), ('full_pipeline', 'Full Pipeline — Download + Whisper'), ('reused', 'Reused — Vectorstore Already Existed')], default='', help_text='Which processing route was taken', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_source',
            field=models.CharField(blank=True, choices=[('vimeo_captions', 'Vimeo Captions (VTT)'), ('whisper', 'Whisper Transcription')], default='', help_text='How the transcript was obtained', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='vimeo_caption_language',
            field=models.CharField(blank=True, default='', help_text='Language code of Vimeo caption track (e.g. en-x-autogen)', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted'), ('REUSED', 'Reused — Vectorstore Already Existed')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
