# Generated by Django 5.0 on 2026-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_processingjob_processing_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='merged_vectorstore_path',
            field=models.CharField(blank=True, default='', help_text='Path to merged (course + SM) vectorstore, relative to MEDIA_ROOT', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='study_material',
            field=models.JSONField(blank=True, help_text='Currently attached study material metadata e.g. {"id": 3, "name": "Week 1 Notes"}', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='study_materials_history',
            field=models.JSONField(blank=True, default=list, help_text='History of replaced study materials (audit log)'),
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('files_count', models.IntegerField(default=0)),
                ('vectorstore_location', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_to_courses', models.ManyToManyField(blank=True, help_text='Courses that have a merged vectorstore for this study material', to='core.course')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
