# Generated by Django 5.0 on 2026-05-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_merged_vectorstore_path_course_study_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='error_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='processed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudyMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Filename as extracted, e.g. "notes.pdf"', max_length=500)),
                ('relative_path', models.CharField(help_text='Path within the zip, e.g. "lectures/week1/notes.pdf"', max_length=1000)),
                ('file_type', models.CharField(blank=True, default='', help_text='File extension, e.g. ".pdf"', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('text_path', models.CharField(blank=True, default='', help_text='Relative path to converted .txt file under study_materials/{name}/text/', max_length=500)),
                ('vectorstore_path', models.CharField(blank=True, default='', help_text='Relative path to per-file vectorstore under study_materials_vectorstore/', max_length=500)),
                ('chunk_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.studymaterial')),
            ],
            options={
                'verbose_name': 'Study Material File',
                'verbose_name_plural': 'Study Material Files',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['study_material', 'status'], name='core_studym_study_m_3b090e_idx')],
            },
        ),
    ]
