# Generated by Django 5.0 on 2026-05-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_study_material_file_and_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='vectorstore_location',
            field=models.CharField(blank=True, default='', help_text='Relative path to merged SM vectorstore under study_materials_vectorstore/complete_vectorstores/', max_length=500),
        ),
        migrations.AlterField(
            model_name='studymaterialfile',
            name='vectorstore_path',
            field=models.CharField(blank=True, default='', help_text='Relative path to per-file vectorstore under study_materials_vectorstore/individual_vectorstores/', max_length=500),
        ),
    ]
